module.exports = [{
        id: 1,
        title: "Self Design Women V Neck Black T-Shirt",
        price: 20,
        description: "Your perfect pack for everyday use and walks in the forest.Slim-fitting style,Women V Neck Black T-Shirt.",
        category: "women",
        image: "https://rukminim1.flixcart.com/image/452/542/kdhphu80/top/r/s/r/s-tipsy-351-black-s-antezik-original-imafudzysmg58fkv.jpeg?q=50",

        rate: 3.9,
        count: 120,
    },
    {
        id: 2,
        title: "Casual Puff Sleeves Solid Women Dark Blue Top",
        price: 22.3,
        description: "Oomph! offers all kinds of tops for both women and girls - tops for women under 500, tops for girls new fashion western, women tops, top for girls, top for women western wear.",
        category: "women",
        image: "https://rukminim1.flixcart.com/image/452/542/koad9jk0/top/j/m/t/xl-ulss19tp09-37-744-uptownie-lite-original-imag2sytmbfzfnmq.jpeg?q=50",

        rate: 4.1,
        count: 259,
    },
    {
        id: 3,
        title: "Mens Cotton Jacket",
        price: 55.99,
        description: "great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors.",
        category: "men",
        image: "https://rukminim1.flixcart.com/image/800/960/kppt47k0/shirt/e/r/p/s-double-threshold-blue-shirt-marmic-fab-original-imag3vucjygkyxbb.jpeg?q=50",

        rate: 4.7,
        count: 500,
    },
    {
        id: 4,
        title: "Mens Casual Slim Fit",
        price: 15.99,
        description: "The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
        category: "men",
        image: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",

        rate: 2.1,
        count: 430,
    },
    {
        id: 5,
        title: "Solid Georgette Blend Stitched Flared/A-line Gown  (Light Green)",
        price: 100,
        description: "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
        category: "women",
        image: "https://rukminim1.flixcart.com/image/452/542/kpcy5jk0/gown/0/u/l/na-xxl-short-sleeve-stitched-ss-04-jash-creation-na-original-imag3hyd6ttywyv4.jpeg?q=50",

        rate: 4.6,
        count: 400,
    },
    {
        id: 6,
        title: "Boys Festive & Party Shirt, Waistcoat and Pant Set  (Black Pack of 1) ",
        price: 2000,
        description: "Net Semi-Stitched Gown Give any season a pop of color with this red net anarkali Lehenga choli by Anjani Lifestyle. The crisp, smooth texture of Square net with a Soft silk lining makes it easy to carry off and gives a look of regal elegance making it the ideal attire for any important ethic event.",
        category: "kids",
        image: "https://rukminim1.flixcart.com/image/452/542/ksru0sw0/kids-ethnic-set/v/x/f/2-3-years-digibc001-digimart-original-imag69ha2hensycf.jpeg?q=50",

        rate: 4.1,
        count: 70,
    },
    {
        id: 7,
        title: "Embroidered Semi Stitched Lehenga Choli  (Black)",
        price: 5000,
        description: " Shop from a wide range of beautifully Embroidered Lehenga Choli from Nir Fashion on UrbanStore . Pair this piece with heels or flats and matching jewelry for a stunning look.",
        category: "women",
        image: "https://rukminim1.flixcart.com/image/452/542/ksoz53k0/lehenga-choli/0/e/r/free-full-sleeve-semi-stitched-lehenga-choli-vizmark-original-imag674thrx5hapf.jpeg?q=50",

        rate: 4.5,
        count: 400,
    },

    {
        id: 8,
        title: "Casual Regular Sleeves Laser Cut, Woven, Solid, Self Design, Lace, Embellished Women Dark Green Top",
        price: 10.99,
        description: " Laser Cut, Woven, Solid, Self Design, Lace, Embellished.Women can style a trendy tops with jeggings and sandals to nail the perfect casual look. Try pairing crop tops with denim shorts for the perfect summer look ",
        category: "women",
        image: "https://rukminim1.flixcart.com/image/452/542/klo27bk0/top/c/l/p/m-147tkr2785a-selvia-original-imagyq82gwvysrqy.jpeg?q=50",

        rate: 1.9,
        count: 100,
    },
    {
        id: 9,
        title: "Girls Festive & Party Kurta, Dhoti Pant & Dupatta Set  (Pink Pack of 3)",
        price: 64,
        description: "Kurta, Dhoti Pant & Dupatta Set,Check out the amazing collection of topwear for women online and select the ones that suit you the best. Browse through stylish girls’s topwear that are offered by popular brands, such as Only, Jockey, U&F, Darzi, Ann Springs, and more.",
        category: "kids",
        image: "https://rukminim1.flixcart.com/image/452/542/jt395zk0/kids-ethnic-set/d/2/r/10-11-years-pink-dhoti-kurta-xomantic-fashion-original-imafe5gfkf5qjpvw.jpeg?q=50",

        rate: 3.3,
        count: 203,
    },
    {
        id: 10,
        title: "Boys Printed Pure Cotton T Shirt  (White, Pack of 1)",
        price: 109,
        description: "Boys Printed Pure Cotton T Shirt ,The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description",
        category: "kids",
        image: "https://rukminim1.flixcart.com/image/452/542/kjom6q80-0/kids-t-shirt/a/r/v/11-12-years-boy-20-hd-fl-wht-blk-watched-maniac-original-imafz7fhygnftgxh.jpeg?q=50",

        rate: 2.9,
        count: 470,
    },
    {
        id: 11,
        title: "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
        price: 109,
        description: "3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAID, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
        category: "electronics",
        image: "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
        rate: 4.8,
        count: 319,
    },
    {
        id: 12,
        title: "Girls Lehenga Choli Ethnic Wear, Party Wear Embroidered Lehenga, Choli and Dupatta Set  (Light Blue, Pack of 1)",
        price: 114,
        description: "Lehenga, Choli and Dupatta Set,Check out the amazing collection of topwear for women online and select the ones that suit you the best. Browse through stylish girls’s topwear that are offered by popular brands, such as Only, Jockey, U&F, Darzi, Ann Springs, and more.",
        category: "kids",
        image: "https://rukminim1.flixcart.com/image/452/542/kkyc9zk0/kids-lehenga-choli/4/h/w/2-3-years-kd-fiona-kedar-fab-original-imagy6vfjp2g43pc.jpeg?q=50",

        rate: 4.8,
        count: 400,
    },
    {
        id: 13,
        title: "MOTOROLA AmphisoundX with HDMI Arc 160 W Bluetooth Soundbar  (Metallic grey, 2.1 Channel)",
        price: 599,
        description: "Model Name-AmphisoundX with HDMI Arc with Type Soundbar and it also has  Bluetooth with Power Output (RMS) as- 160 W in black color. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz",
        category: "electronics",
        image: "https://rukminim1.flixcart.com/image/612/612/ku4ezrk0/speaker/soundbar/x/g/s/amphisoundx-motorola-original-imag7b6meddjy3we.jpeg?q=70",

        rate: 4.3,
        count: 7000,
    },
    {
        id: 14,
        title: "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ",
        price: 999.99,
        description: "49 INCH SUPER ULTRAWIDE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag",
        category: "electronics",
        image: "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",

        rate: 2.2,
        count: 140,
    },
    {
        id: 15,
        title: "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
        price: 56.99,
        description: "Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates",
        category: "women",
        image: "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",

        rate: 2.6,
        count: 235,
    },
    {
        id: 16,
        title: "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
        price: 29.95,
        description: "100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON",
        category: "women",
        image: "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",

        rate: 2.9,
        count: 340,
    },
    {
        id: 17,
        title: "Rain Jacket Women Windbreaker Striped Climbing Raincoats",
        price: 39.99,
        description: "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
        category: "women",
        image: "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",

        rate: 3.8,
        count: 679,
    },
    {
        id: 18,
        title: "BTS Poly Suit cl Solid Men Track Suit",
        price: 9.85,
        description: "95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem",
        category: "men",
        image: "https://rukminim1.flixcart.com/image/452/542/ktop5e80/track-suit/a/c/g/m-58584106-puma-original-imag6z63j8vjs65z.jpeg?q=50",

        rate: 4.7,
        count: 130,
    },
    {
        id: 19,
        title: "APPLE Airpods Pro with MagSafe Charging Case Bluetooth Headset  (White, True Wireless)",
        price: 200,
        description: "APPLE Airpods Pro with More than 24 hours of total listening time with the MagSafe Charging Case-Transparency mode for hearing and interacting with the world around you-Three sizes of soft, tapered silicone tips for a customizable fit | Sweat and water resistant",
        category: "electronics",
        image: "https://rukminim1.flixcart.com/image/612/612/kpinwy80/headphone/r/1/q/mwp22hn-a-apple-original-imag3qe9eqkfhmg8.jpeg?q=70",

        rate: 4.5,
        count: 146,
    },
    {
        id: 20,
        title: "DANVOUY Womens T Shirt Casual Cotton Short",
        price: 12.99,
        description: "95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.",
        category: "women",
        image: "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",

        rate: 3.6,
        count: 145,
    },
];